/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Restaurant.Menu;

import Business.EcoSystem;
import Business.Restaurant.Dishes;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhetr
 */
public class ManageMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMenuJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
    private Restaurant restaurant;
    private Dishes dishes;

    public ManageMenuJPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount userAccount) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = userAccount;
        populateMenuTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageMenuInfo = new javax.swing.JLabel();
        lblDishName = new javax.swing.JLabel();
        lblDishDescription = new javax.swing.JLabel();
        lblDishPrice = new javax.swing.JLabel();
        txtDishDescription = new javax.swing.JTextField();
        txtDishPrice = new javax.swing.JTextField();
        txtDishName = new javax.swing.JTextField();
        btnCreateMenu = new javax.swing.JButton();
        lblMenuInfo = new javax.swing.JLabel();
        scrollCustomerInfo = new javax.swing.JScrollPane();
        tblMenus = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        lblManageMenuInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblManageMenuInfo.setText("Add New Menu ");

        lblDishName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDishName.setText(" Name:");

        lblDishDescription.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDishDescription.setText(" Description:");

        lblDishPrice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDishPrice.setText("Price:");

        btnCreateMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCreateMenu.setText("Add Menu");
        btnCreateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMenuActionPerformed(evt);
            }
        });

        lblMenuInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMenuInfo.setText("Menu Information");

        tblMenus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblMenus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dish Name", "Dish Description", "Dish Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollCustomerInfo.setViewportView(tblMenus);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(222, 222, 222)
                        .addComponent(lblManageMenuInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(btnCreateMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblDishName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDishName, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblDishDescription)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDishDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblDishPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDishPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(99, 99, 99))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(lblMenuInfo)))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scrollCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDishDescription, txtDishName, txtDishPrice});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblManageMenuInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDishName)
                    .addComponent(txtDishName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDishDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDishDescription))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDishPrice)
                    .addComponent(txtDishPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMenuInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(scrollCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDishDescription, lblDishName, lblDishPrice});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDishDescription, txtDishName, txtDishPrice});

    }// </editor-fold>//GEN-END:initComponents

    public void populateMenuTable() {
        Restaurant restaurant = ecosystem.getRestaurantDirectory().getRestaurant(userAccount.getUsername());
        DefaultTableModel dishModel = (DefaultTableModel) tblMenus.getModel();
        dishModel.setRowCount(0);
        for (Dishes dishes : restaurant.getDishesList()) {
            Object[] row = new Object[5];
            row[0] = dishes.getDishName();
            row[1] = dishes.getDishDescripton();
            row[2] = dishes.getPrice();
            dishModel.addRow(row);
        }
    }

    private void btnCreateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMenuActionPerformed
        // TODO add your handling code here:
        if (txtDishName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dish Name cannot be empty.");
            return;
        }
        if (txtDishDescription.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dish Description cannot be empty.");
            return;
        } else if (txtDishPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dish Price cannot be empty.");
            return;
        }
        String numberFormat = "^\\d{0,8}(\\.\\d{1,4})?$";
        if (Pattern.compile(numberFormat).matcher(txtDishPrice.getText()).matches()) {
        } else {
            JOptionPane.showMessageDialog(this, "Dish Price entered is not proper, please enter the price in correct format.");
            return;
        }
        Restaurant restro = ecosystem.getRestaurantDirectory().getRestaurant(userAccount.getUsername());

        String dishName = txtDishName.getText();
        String dishDescripption = txtDishDescription.getText();
        String dishPrice = txtDishPrice.getText();
        Dishes menu = new Dishes(dishName, dishDescripption, dishPrice);
        restro.getDishesList().add(menu);
        txtDishName.setText("");
        txtDishDescription.setText("");
        txtDishPrice.setText("");
        populateMenuTable();

    }//GEN-LAST:event_btnCreateMenuActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMenus.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_CANCEL_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete the selected Dish?", "warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                String dishName = (String) tblMenus.getValueAt(selectedRow, 0);
                String dishDescription = (String) tblMenus.getValueAt(selectedRow, 1);
                String deshPrice = (String) tblMenus.getValueAt(selectedRow, 2);
                Restaurant restro = ecosystem.getRestaurantDirectory().getRestaurant(userAccount.getUsername());
                Dishes dish = restro.getOneDish(dishName);
                restro.getDishesList().remove(dish);
                populateMenuTable();
            }
    }//GEN-LAST:event_btnDeleteActionPerformed
    else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete the Dishes in the Cart.");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateMenu;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel lblDishDescription;
    private javax.swing.JLabel lblDishName;
    private javax.swing.JLabel lblDishPrice;
    private javax.swing.JLabel lblManageMenuInfo;
    private javax.swing.JLabel lblMenuInfo;
    private javax.swing.JScrollPane scrollCustomerInfo;
    private javax.swing.JTable tblMenus;
    private javax.swing.JTextField txtDishDescription;
    private javax.swing.JTextField txtDishName;
    private javax.swing.JTextField txtDishPrice;
    // End of variables declaration//GEN-END:variables
}
