/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.Customer.Customer;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Restaurant.Order;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dgoda
 */
public class DeliverymanAssignmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliverymanAssignmentJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private Order order;

    public DeliverymanAssignmentJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecosystem, Order order) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        this.order = order;
        populateDeliveryManTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeliverymanAssignment = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnOrderAssignment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAssignDeliveryman = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 204));

        lblDeliverymanAssignment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDeliverymanAssignment.setText("Assign Delivery Man");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnOrderAssignment.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnOrderAssignment.setText("Assign Order");
        btnOrderAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderAssignmentActionPerformed(evt);
            }
        });

        tblAssignDeliveryman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Deliveryman Name", "Deliveryman Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAssignDeliveryman);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(235, 235, 235)
                        .addComponent(lblDeliverymanAssignment))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(btnOrderAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliverymanAssignment)
                    .addComponent(btnBack))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnOrderAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBack, lblDeliverymanAssignment});

    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderAssignmentActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAssignDeliveryman.getSelectedRow();
        if (selectedRow >= 0) {
            DeliveryMan deliveryMan = (DeliveryMan) tblAssignDeliveryman.getValueAt(selectedRow, 0);
            deliveryMan.getOrderList().add(order);
            order.setStatus("Assigned to Deliveryman");
            Customer customer = ecosystem.getCustomerDirectory().getCustomer(order.getCustomerName());
            for (Order ord : customer.getOrderList()) {
                if (ord.getOrderId().equalsIgnoreCase(order.getOrderId())) {
                    ord.setStatus("Assigned to Deliveryman");
                    JOptionPane.showMessageDialog(null, "Status Updated Successfully, Assigned for Deliveryman.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to assign the order to a Delivery Man");
        }
    }//GEN-LAST:event_btnOrderAssignmentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    public void populateDeliveryManTable() {
        DefaultTableModel deliverymanModel = (DefaultTableModel) tblAssignDeliveryman.getModel();
        deliverymanModel.setRowCount(0);
        ArrayList<DeliveryMan> deliveryMan = ecosystem.getDeliveryManDirectory().getDeliverymanList();
        for (DeliveryMan delMan : deliveryMan) {
            Object[] row = new Object[2];
            row[0] = delMan;
            row[1] = delMan.getDeliverymanNumber();
            deliverymanModel.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOrderAssignment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDeliverymanAssignment;
    private javax.swing.JTable tblAssignDeliveryman;
    // End of variables declaration//GEN-END:variables
}
