/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dgoda
 */
public class ManageRestaurantInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurantInfoJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAccount;

    public ManageRestaurantInfoJPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount userAccount) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = userAccount;
        txtRestaurantUsername.setText(userAccount.getUsername());
        populateRestaurantInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblManageRestaurantInfo = new javax.swing.JLabel();
        lblRestaurantName = new javax.swing.JLabel();
        txtRestaurantUsername = new javax.swing.JTextField();
        lblRestaurantUsername = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtRestaurantAddress = new javax.swing.JTextField();
        txtRestaurantNumber = new javax.swing.JTextField();
        txtRestaurantName = new javax.swing.JTextField();
        lblRestaurantAddress = new javax.swing.JLabel();
        lblRestaurantNumber = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblManageRestaurantInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblManageRestaurantInfo.setText("Manage Restaurant Information");

        lblRestaurantName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRestaurantName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRestaurantName.setText("Restaurant Name:");

        txtRestaurantUsername.setEditable(false);
        txtRestaurantUsername.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtRestaurantUsername.setEnabled(false);
        txtRestaurantUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRestaurantUsernameActionPerformed(evt);
            }
        });

        lblRestaurantUsername.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRestaurantUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRestaurantUsername.setText("Restaurant Username:");

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtRestaurantAddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtRestaurantAddress.setEnabled(false);
        txtRestaurantAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRestaurantAddressActionPerformed(evt);
            }
        });

        txtRestaurantNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtRestaurantNumber.setEnabled(false);

        txtRestaurantName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtRestaurantName.setEnabled(false);

        lblRestaurantAddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRestaurantAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRestaurantAddress.setText("Address:");

        lblRestaurantNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRestaurantNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRestaurantNumber.setText("Phone Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(lblManageRestaurantInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblRestaurantName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRestaurantNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRestaurantAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblRestaurantUsername))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRestaurantName)
                            .addComponent(txtRestaurantNumber)
                            .addComponent(txtRestaurantAddress)
                            .addComponent(txtRestaurantUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblRestaurantAddress, lblRestaurantName, lblRestaurantNumber});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtRestaurantAddress, txtRestaurantName, txtRestaurantNumber, txtRestaurantUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManageRestaurantInfo))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestaurantUsername)
                    .addComponent(txtRestaurantUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestaurantName)
                    .addComponent(txtRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestaurantNumber)
                    .addComponent(txtRestaurantNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestaurantAddress)
                    .addComponent(txtRestaurantAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblRestaurantAddress, lblRestaurantName, lblRestaurantNumber, lblRestaurantUsername});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtRestaurantAddress, txtRestaurantName, txtRestaurantNumber, txtRestaurantUsername});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSave, btnUpdate});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtRestaurantName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Restaurant Name cannot be empty.");
            return;
        }
        if (txtRestaurantAddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Restaurant Address cannot be empty.");
            return;
        } else if (txtRestaurantNumber.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Restaurant Number cannot be empty.");
            return;
        }
        String numberFormat = "^\\(?(\\d{3})\\)?[- ]?(\\d{3})[- ]?(\\d{4})$";
        if (Pattern.compile(numberFormat).matcher(txtRestaurantNumber.getText()).matches()) {
            System.out.println("Phone number entered is correct.");
        } else {
            JOptionPane.showMessageDialog(this, "Phone Number entered is not proper, please enter the number in correct format.");
            return;
        }
        
        Restaurant restaurant = ecosystem.getRestaurantDirectory().getRestaurant(userAccount.getUsername());
        ecosystem.getRestaurantDirectory().updateRestaurantInfo(restaurant, txtRestaurantName.getText(), txtRestaurantUsername.getText(), txtRestaurantAddress.getText(), txtRestaurantNumber.getText());

        btnUpdate.setEnabled(true);
        txtRestaurantName.setEnabled(false);
        txtRestaurantNumber.setEnabled(false);
        txtRestaurantAddress.setEnabled(false);
        populateRestaurantInfo();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtRestaurantName.setEnabled(true);
        txtRestaurantNumber.setEnabled(true);
        txtRestaurantAddress.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    public void populateRestaurantInfo(){
        for(Restaurant restaurant: ecosystem.getRestaurantDirectory().getRestaurantList()){
            if(restaurant.getRestaurantUsername().equals(userAccount.getUsername())){
                txtRestaurantName.setText(restaurant.getRestaurantName());
                txtRestaurantNumber.setText(restaurant.getRestaurantNumber());
                txtRestaurantAddress.setText(restaurant.getRestaurantAddress());
            }
        }
    }
    
    private void txtRestaurantUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRestaurantUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRestaurantUsernameActionPerformed

    private void txtRestaurantAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRestaurantAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRestaurantAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblManageRestaurantInfo;
    private javax.swing.JLabel lblRestaurantAddress;
    private javax.swing.JLabel lblRestaurantName;
    private javax.swing.JLabel lblRestaurantNumber;
    private javax.swing.JLabel lblRestaurantUsername;
    private javax.swing.JTextField txtRestaurantAddress;
    private javax.swing.JTextField txtRestaurantName;
    private javax.swing.JTextField txtRestaurantNumber;
    private javax.swing.JTextField txtRestaurantUsername;
    // End of variables declaration//GEN-END:variables
}
